theme: minima
title: super cool web site
author: me :)
email: wvign1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  an awesome web site made by me :]

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
